apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: botg-staging

resources:
  - patternlayer-configmap.yaml

labels:
  - pairs:
      deployment: patternlayer-phase1
      timestamp: "2024-01-15"
